spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/loooSwc/SpringcloudConfig/
          searchPaths: respo
    label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8300


#spring.cloud.config.server.git.uri=https://github.com/forezp/SpringcloudConfig/
#spring.cloud.config.server.git.searchPaths=respo
#spring.cloud.config.label=master
#spring.cloud.config.server.git.username=357428589@qq.com
#spring.cloud.config.server.git.password=somous19940110